export default {
  c1: "var(--c1)",
  c2: "var(--c2)",
  c3: "var(--c3)",
  c4: "var(--c4)",
  c5: "var(--c5)",
  c6: "var(--c6)",
  c7: "var(--c7)",
  c8: "var(--c8)",
  c9: "var(--c9)",
  c10: "var(--c10)",
  c1: "var(--c1)",
  c1: "var(--c1)",
  red: "--z-red",
  green: "--z-green",
  bgreen: "--z-bgreen",
  yellow: "--z-yellow",
  blue: "--z-blue",
};
